# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.mycompany.com:
  peer0.myorg.mycompany.com:
  peer1.myorg.mycompany.com:

networks:
  mynet:

services:

  orderer.mycompany.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.mycompany.com
    container_name: orderer.mycompany.com
    networks:
      - mynet

  peer0.myorg.mycompany.com:
    container_name: peer0.myorg.mycompany.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.myorg.mycompany.com
    networks:
      - mynet

  peer1.myorg.mycompany.com:
    container_name: peer1.myorg.mycompany.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.myorg.mycompany.com
    networks:
      - mynet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.myorg.mycompany.com:7051
      - CORE_PEER_LOCALMSPID=MyOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg.mycompany.com/peers/peer0.myorg.mycompany.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg.mycompany.com/peers/peer0.myorg.mycompany.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg.mycompany.com/peers/peer0.myorg.mycompany.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg.mycompany.com/users/Admin@myorg.mycompany.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.mycompany.com
      - peer0.myorg.mycompany.com
      - peer1.myorg.mycompany.com
    networks:
      - mynet
